#ifndef W_SRC_NDN_CXX_CONFIG_HPP_WAF
#define W_SRC_NDN_CXX_CONFIG_HPP_WAF

#define NDN_CXX_HAVE_STD_TO_STRING 1
#define NDN_CXX_HAVE_VECTOR_INSERT_ERASE_CONST_ITERATOR 1
#define NDN_CXX_HAVE_IS_DEFAULT_CONSTRUCTIBLE 1
#define NDN_CXX_HAVE_IS_NOTHROW_MOVE_CONSTRUCTIBLE 1
#define NDN_CXX_HAVE_IS_NOTHROW_MOVE_ASSIGNABLE 1
#define NDN_CXX_HAVE_RT
#define NDN_CXX_HAVE_PTHREAD 1
#define NDN_CXX_HAVE_SQLITE3 1
#define NDN_CXX_SYSCONFDIR "./etc"
#define ENABLE_LOGGING

#endif /* W_SRC_NDN_CXX_CONFIG_HPP_WAF */
